# Generated by Django 4.0.5 on 2022-06-08 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, verbose_name='NAME')),
                ('slug', models.SlugField(max_length=500, unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='TEXT REMEMBER')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='TIME CREATE')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='TIME UPDATE')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='USERS')),
            ],
        ),
    ]
